version: '3.8'
services:
  db:
    image: mongo
    container_name: mongo-db
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./tmp/data/db:/data/db
  cache:
    image: redis
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./tmp/data/cache:/data/cache
  server:
    image: mercedes722s/url-shortener-backend
    container_name: server
    ports:
      - "3000:3000"
    command: >
      /bin/bash -c "
      sleep 10;
      npm run seed;
      sleep 5;
      npm run start;"
    environment:
      PORT: "3000"
      NODE_ENV: "development"
      MONGODB_URI: "mongodb://db:27017"
      REDISCLOUD_URL: "redis://cache:6379"
      JWT_SECRET: "123456"
  web:
    image: mercedes722s/url-shortener-frontend
    container_name: web
    ports:
      - "8080:8080"
    command: >
      /bin/bash -c "
      npm run serve;"
    environment:
      PORT: "8080"
      VUE_APP_DOMAIN: "http://localhost:8080/#/"
      VUE_APP_BASEURL: "http://localhost:3000/api"